176 cadastro empresa
UnBArqDsw/2020.1_G12_Stock_Backend pull request #14
Opened 2020-10-31 12:54 UTC by micaellagouveia

## Descrição
Criação das rotas de cadastro de empresa e usuário owner.

2020-11-03 21:13 UTC, sofiapatrocinio approved these changes

2020-11-05 18:08 UTC, GabrielDVpereira requested changes

2020-11-05 18:08 UTC, GabrielDVpereira commented on src/app/StockBase/CollaboratorBase.js
> +      console.log(collaborators);
remover esses logs

2020-11-05 18:08 UTC, GabrielDVpereira commented on src/app/StockBase/CompanyBase.js
> +      console.log(CompanyInfo.companyDocument);
remover log

2020-11-05 18:08 UTC, GabrielDVpereira commented on src/app/StockBase/CompanyBase.js
> +      console.log(company);
remover log

2020-11-05 18:08 UTC, GabrielDVpereira commented on src/app/StockBase/CompanyBase.js
> +      throw { status: 401, message: 'Verifique seu documento.' };
acredito que um status para esse caso seja de 400. Geralmente 401 significa não autenticado e é usado pra autenticação

2020-11-05 18:08 UTC, GabrielDVpereira commented on src/database/migrations/20201009015447-collaborators.js
> +      email: {
nesse caso é melhor criar uma nova migration para adicionar essa coluna

2020-11-05 18:08 UTC, GabrielDVpereira commented on src/database/migrations/20201009004057-company.js
> +        allowNull: true,
cria uma nova migration para alterar esse campo

2020-11-09 17:15 UTC, GabrielDVpereira approved these changes

2020-11-09 17:15 UTC, merged