187 adição remoção colaborador
UnBArqDsw/2020.1_G12_Stock_Backend pull request #15
Opened 2020-11-04 21:30 UTC by sofiapatrocinio

## Descrição 

- Adição do atributo booleano 'activate' ao colaborador
- Adição das rotas de update profile e update collaborator
- Verificação do atributo 'activate' ao realizar login

## Resolve (Issues)

#187

2020-11-05 18:15 UTC, GabrielDVpereira requested changes

2020-11-05 18:15 UTC, GabrielDVpereira commented on src/app/StockBase/CollaboratorBase.js
> +    if (!collaborator) throw { status: 401, message: 'Usuário não encontrado' };
acho que 401 não se encaixa nesse caso. acredito que 404 seja mais adequado, se idCollaborator estiver sendo passado por parametro

2020-11-05 18:15 UTC, GabrielDVpereira commented on src/app/StockBase/CollaboratorBase.js
> +    if (!collaborator) throw { status: 401, message: 'Usuário não encontrado' };
acho que 401 n cabe pra esse caso. Melhor seria 404, se idCollaborator for passado pela rota, se n pode ser 400

2020-11-07 12:50 UTC, GabrielDVpereira approved these changes

2020-11-07 13:09 UTC, pedroeagle requested changes
Vi que estão setando as níveis de acesso manualmente no front..seria melhor se fosse feita uma requisição a tabela de níveis de acesso até mesmo pra consultar as informações de cada nível de acesso.

2020-11-07 19:43 UTC, sofiapatrocinio commented
@pedroeagle resolvido! :)

2020-11-08 18:45 UTC, pedroeagle requested changes

2020-11-08 18:45 UTC, pedroeagle commented on src/database/migrations/20201009015447-collaborators.js
> +      activate: {
Esse novo atributo a tabela collaborator deveria ser uma outra migration

2020-11-08 18:45 UTC, pedroeagle commented on src/app/StockBase/AccessLevelBase.js
> +    return accessLevel;
ao invés de fazer aquele switch case lá do front, deveria pegar a description retornada nesse listAll aqui.

2020-11-09 17:20 UTC, GabrielDVpereira requested changes

2020-11-09 17:20 UTC, GabrielDVpereira commented on src/app/StockBase/AccessLevelBase.js
> +    console.log('Base' + accessLevel);
remover console.log

2020-11-09 17:20 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +          message: 'Its not possible to update access level or status',
Estamos usando as mensagens de erro em pt.

2020-11-09 17:20 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +          .json({ message: 'Collaborator updated successfully.' });
Estamos usando as mensagens de erro em pt.

2020-11-09 17:20 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +      return res.status(400).json({ message: 'Error updating Collaborator.' });
Estamos usando as mensagens de erro em pt.

2020-11-09 17:20 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +          message: 'Its not possible to update collaborator password',
Estamos usando as mensagens de erro em pt.

2020-11-09 17:20 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +          .json({ message: 'Collaborator updated successfully.' });
Estamos usando as mensagens de erro em pt.

2020-11-09 17:20 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +      return res.status(400).json({ message: 'Error updating Collaborator.' });
Estamos usando as mensagens de erro em pt.

2020-11-09 19:24 UTC, pedroeagle approved these changes

2020-11-09 21:24 UTC, pedroeagle approved these changes

2020-11-09 21:44 UTC, GabrielDVpereira approved these changes

2020-11-09 21:44 UTC, merged