188 cadastro produtos
UnBArqDsw/2020.1_G12_Stock_Backend pull request #16
Opened 2020-11-08 18:49 UTC by pedroeagle

## Descrição 

Descrição concisa do que foi feito
Implementação de algumas pequenas funções de listagem de categorias, lotes e produtos para utilização no front. Além disso foi adicionada uma lista de todos os lotes do produto na própria model do produto. Vale lembrar que no nível de banco de dados isso não foi alterado e não deve ser.

2020-11-09 23:54 UTC, sofiapatrocinio commented
Ficou muito bom! Acho que podemos fazer algumas mudanças só pra deixar o caminho do usuário melhor.

No campo de preço acho que poderia ter um texto fixo com um "R$ ...." e o que o usuário preencher, pra não ficar um valor solto
![image](https://user-images.githubusercontent.com/38709421/98609009-2dfa0e80-22cb-11eb-98ef-2dc984b6da70.png)

Aqui, acho que faz mais sentido primeiro vir quantidade, depois unidade de medida, por ser a forma como normalmente escrevemos em tabelas por exemplo
![image](https://user-images.githubusercontent.com/38709421/98609095-584bcc00-22cb-11eb-8c36-56b87b368f6d.png)

Eu redesenhei essa parte de categorias, mas se der muito trabalho pra implementar é só uma ideia haha 
![image](https://user-images.githubusercontent.com/38709421/98609775-e07ea100-22cc-11eb-858e-21568a3bc791.png)
Os pontos que quero levantar são:

- O botão vermelho chama atenção e acho que deve ser usado pra ações destrutivas
- Acho melhor deixar o modal com um botão de ação só embaixo, pra não confundir o usuário


![image](https://user-images.githubusercontent.com/38709421/98609908-318e9500-22cd-11eb-8f10-b0bbeb0116d8.png)

- Aqui acho que não precisa ter data de entrada, acho que devemos pegar essa data de acordo com o dia que o usuário tá executando a ação

- Preço de compra a mesma coisa do preço no modal de adicionar produto 

- Falta placeholder nos campos pra melhor explicação, principalmente quantidade

E por último: descrição precisa mesmo ser obrigatório em lote e categoria?

2020-11-10 00:11 UTC, sofiapatrocinio approved these changes

2020-11-10 00:14 UTC, sofiapatrocinio commented
Ficou muito bom! Pegar o idCompany pelo token ficou ótimo.
Comentei no front sobre qual a real necessidade de em lote e categoria o campo descrição ser obrigatório. Seria bom revermos isso...

2020-11-10 00:17 UTC, sofiapatrocinio requested changes
Ficou muito bom! Pegar o idCompany pelo token ficou ótimo.
Comentei no front sobre qual a real necessidade de em lote e categoria o campo descrição ser obrigatório. Seria bom revermos isso...

2020-11-10 20:13 UTC, micaellagouveia approved these changes
Show, ficou ótimooo

2020-11-10 21:20 UTC, sofiapatrocinio approved these changes

2020-11-10 21:23 UTC, merged