196 nivel colaborador
UnBArqDsw/2020.1_G12_Stock_Backend pull request #17
Opened 2020-11-11 00:30 UTC by sofiapatrocinio

## Descrição 

Adição da rota de load collaborator passando idCollaborator como parâmetro. Essa rota é utilizada para retornar os dados do colaborador na hora de editar

## Resolve (Issues)

#196 https://github.com/UnBArqDsw/2020.1_G12_Stock/issues/196

2020-11-12 20:29 UTC, pedroeagle approved these changes

2020-11-13 17:06 UTC, GabrielDVpereira requested changes

2020-11-13 17:06 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +      const collaborator = await CollaboratorBase.listCollaborator(
acho que cabe uma validação aqui caso ele n ache o colaborador, retornar um erro

2020-11-13 18:55 UTC, GabrielDVpereira approved these changes

2020-11-13 18:55 UTC, merged