194 remover itens
UnBArqDsw/2020.1_G12_Stock_Backend pull request #19
Opened 2020-11-14 15:04 UTC by pedroeagle

## Descrição 
 Adição de algumas rotas para remoção de produtos e lotes do estoque. 

## Resolve [194](https://github.com/UnBArqDsw/2020.1_G12_Stock/issues/194)

2020-11-15 16:34 UTC, GabrielDVpereira requested changes

2020-11-15 16:34 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +  async min(req, res) {
Não entendi o nome desse método com o que ele faz, se puder só trocar pra um nome mais descritivo

2020-11-15 16:34 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +      console.log(response.dataValues);
remover console.log

2020-11-15 16:34 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +      console.log(response.dataValues);
remover console.log

2020-11-15 16:34 UTC, GabrielDVpereira commented on src/app/controllers/CollaboratorController.js
> +  async find(req, res) {
Trocar esse nome para um mais descritivo tipo findCollaboratorById ou algo do tipo

2020-11-16 11:21 UTC, pedroeagle commented on src/app/controllers/CollaboratorController.js
> +  async min(req, res) {
a rota de collaborator retorna tudo do collaborator e eu precisava só do nome dele

2020-11-18 14:40 UTC, micaellagouveia approved these changes

2020-11-18 20:09 UTC, sofiapatrocinio requested changes

2020-11-18 20:09 UTC, sofiapatrocinio commented on src/app/StockBase/LotBase.js
> +    console.log(product);
Retirar console.log

2020-11-20 00:16 UTC, sofiapatrocinio approved these changes

2020-11-20 00:20 UTC, GabrielDVpereira approved these changes

2020-11-20 00:20 UTC, merged